# Generated by Django 5.0.9 on 2026-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Comments are hidden from the public until an admin approves them.'),
        ),
    ]
